/// Cookie file helpers (pure, unit-tested).
///
/// Single source of truth for the Netscape `cookies.txt` format shared by
/// the WebView login flow, paste-import, and per-site profile regen.
/// Mirrors ytdlnis (`cacheDir/cookies.txt`, Netscape, app-private, no
/// special Android permission) without its merge-dedup bug.
library;

/// Header stamped on every generated file (ytdlnis-compatible first line
/// so files stay interchangeable with pasted ytdlnis exports).
const String kCookieFileHeader =
    '# Netscape HTTP Cookie File\n# Generated by TrueStream WebView';

class NetscapeCookie {
  final String domain;
  final String includeSubdomains; // 'TRUE' or 'FALSE'
  final String path;
  final String secure; // 'TRUE' or 'FALSE'
  final String expiration;
  final String name;
  final String value;
  final bool isHttpOnly;

  const NetscapeCookie({
    required this.domain,
    required this.includeSubdomains,
    required this.path,
    required this.secure,
    required this.expiration,
    required this.name,
    required this.value,
    this.isHttpOnly = false,
  });

  factory NetscapeCookie.fromLine(String line) {
    bool isHttpOnly = false;
    String cleanLine = line.trim();
    if (cleanLine.startsWith('#HttpOnly_')) {
      isHttpOnly = true;
      cleanLine = cleanLine.substring('#HttpOnly_'.length);
    }
    final parts = cleanLine.split('\t');
    if (parts.length < 7) {
      throw FormatException('Invalid Netscape cookie line: $line');
    }
    return NetscapeCookie(
      domain: parts[0],
      includeSubdomains: parts[1],
      path: parts[2],
      secure: parts[3],
      expiration: parts[4],
      name: parts[5],
      value: parts.sublist(6).join('\t'),
      isHttpOnly: isHttpOnly,
    );
  }

  String toLine() {
    final prefix = isHttpOnly ? '#HttpOnly_' : '';
    return '$prefix$domain\t$includeSubdomains\t$path\t$secure\t$expiration\t$name\t$value';
  }

  /// Merge key: one entry per domain+name (last write wins).
  String get mergeKey => '$domain\x00$name';
}

/// Parse valid Netscape data lines out of pasted text (header lines and
/// blanks skipped; `#HttpOnly_` lines kept). Never throws.
List<NetscapeCookie> parseNetscapeLines(String text) {
  final out = <NetscapeCookie>[];
  for (final raw in text.split('\n')) {
    final line = raw.trim();
    if (line.isEmpty) continue;
    if (line.startsWith('#') && !line.startsWith('#HttpOnly_')) continue;
    try {
      out.add(NetscapeCookie.fromLine(line));
    } catch (_) {
      // Skip corrupt lines — paste boxes are messy.
    }
  }
  return out;
}

/// Merge data lines by domain+name (later lists win). Fixes the ytdlnis
/// whole-content append bug: identical lines never duplicate.
List<String> mergeCookieLines(List<List<String>> sources) {
  final merged = <String, String>{};
  for (final lines in sources) {
    for (final raw in lines) {
      final line = raw.trim();
      if (line.isEmpty) continue;
      try {
        final c = NetscapeCookie.fromLine(line);
        merged[c.mergeKey] = c.toLine();
      } catch (_) {
        // Skip — never let one bad line kill the file.
      }
    }
  }
  return merged.values.toList();
}

/// Render the full file content (header + lines).
String buildCookieFile(List<String> lines) {
  final buf = StringBuffer()..writeln(kCookieFileHeader)..writeln();
  for (final line in lines) {
    buf.writeln(line);
  }
  return buf.toString();
}

/// Domain for header-string pastes, derived from [siteUrl]'s host
/// (leading dot so subdomains match, like browsers send).
String? domainForUrl(String siteUrl) {
  Uri? uri;
  try {
    var u = siteUrl.trim();
    if (!u.contains('://')) u = 'https://$u';
    uri = Uri.parse(u);
  } catch (_) {
    return null;
  }
  final host = uri.host.toLowerCase();
  if (host.isEmpty || !host.contains('.')) return null;
  if (!RegExp(r'^[a-z0-9.-]+$').hasMatch(host)) return null;
  return host.startsWith('.') ? host : '.$host';
}

/// Parse pasted cookie text into Netscape data lines. Accepts:
/// (a) full/partial Netscape files (with or without the header), and
/// (b) raw `Cookie:` header strings (`name=value; name2=value2`) using
/// [siteUrl] for the domain. Returns empty when nothing parses.
List<String> parsePastedCookies(String text, String siteUrl) {
  final netscape = parseNetscapeLines(text);
  if (netscape.isNotEmpty) {
    return netscape.map((c) => c.toLine()).toList();
  }
  final domain = domainForUrl(siteUrl);
  if (domain == null) return [];
  final out = <String>[];
  // Strip a leading "Cookie:" label if the user pasted the whole header.
  var body = text.trim();
  if (body.toLowerCase().startsWith('cookie:')) {
    body = body.substring('cookie:'.length);
  }
  final expiry = (DateTime.now().millisecondsSinceEpoch ~/ 1000) +
      10 * 365 * 24 * 60 * 60;
  for (final pair in body.split(';')) {
    final eq = pair.indexOf('=');
    if (eq <= 0) continue;
    final name = pair.substring(0, eq).trim();
    final value = pair.substring(eq + 1).trim();
    if (name.isEmpty || name.contains(RegExp(r'\s')) || value.isEmpty) continue;
    out.add(NetscapeCookie(
      domain: domain,
      includeSubdomains: 'TRUE',
      path: '/',
      secure: domain.contains('.') ? 'TRUE' : 'FALSE',
      expiration: expiry.toString(),
      name: name,
      value: value,
    ).toLine());
  }
  return out;
}
