import 'package:flutter_test/flutter_test.dart';
import 'package:grablytic/core/utils/cookie_store.dart';

void main() {
  group('NetscapeCookie', () {
    test('round-trips a data line, keeps #HttpOnly_', () {
      const line = '.youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tabc123';
      final c = NetscapeCookie.fromLine(line);
      expect(c.domain, '.youtube.com');
      expect(c.name, 'SID');
      expect(c.toLine(), line);
      final h = NetscapeCookie.fromLine('#HttpOnly_$line');
      expect(h.isHttpOnly, isTrue);
      expect(h.toLine(), '#HttpOnly_$line');
    });

    test('rejects short lines', () {
      expect(() => NetscapeCookie.fromLine('a\tb\tc'), throwsFormatException);
    });
  });

  group('mergeCookieLines', () {
    test('dedupes by domain+name, later wins, drops garbage', () {
      const old_ = '.a.com\tTRUE\t/\tTRUE\t1\tSID\told';
      const new_ = '.a.com\tTRUE\t/\tTRUE\t2\tSID\tnew';
      const other = '.b.com\tTRUE\t/\tTRUE\t1\tSID\tx';
      final merged = mergeCookieLines([
        [old_, other],
        [new_, 'garbage line', ''],
      ]);
      expect(merged, hasLength(2));
      expect(merged.any((l) => l.endsWith('\tSID\tnew')), isTrue);
      expect(merged.any((l) => l.startsWith('.b.com')), isTrue);
    });
  });

  group('parsePastedCookies', () {
    test('accepts Netscape with ytdlnis-style header', () {
      const pasted = '# Netscape HTTP Cookie File\n'
          '# WebView Generated by the YTDLnis app\n'
          '.youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tabc';
      final lines = parsePastedCookies(pasted, 'https://youtube.com');
      expect(lines, hasLength(1));
      expect(lines.first, contains('SID'));
    });

    test('accepts raw Cookie header string with site domain', () {
      final lines = parsePastedCookies(
        'SID=abc123; HSID=def456; badpair; =noname',
        'youtube.com',
      );
      expect(lines, hasLength(2));
      expect(lines.first.startsWith('.youtube.com\tTRUE'), isTrue);
    });

    test('garbage yields empty (UI shows not-found)', () {
      expect(parsePastedCookies('hello world', 'https://x.test'), isEmpty);
      expect(parsePastedCookies('a=b', 'not a url at all!!! '), isEmpty);
    });
  });

  group('buildCookieFile', () {
    test('stamps header then lines', () {
      const line = '.a.com\tTRUE\t/\tTRUE\t1\tSID\tx';
      final file = buildCookieFile([line]);
      expect(file.startsWith('# Netscape HTTP Cookie File'), isTrue);
      expect(file, contains(line));
    });
  });
}
